workflows:
  ios-workflow:
    name: Build Unsigned IPA
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      # الخطوة 1: تأكد من تكوين iOS وتثبيت تبعيات Flutter
      - name: Setup Flutter & iOS
        script: |
          flutter doctor
          flutter pub get
          cd ios
          pod install
          cd ..

      # الخطوة 2: بناء IPA بدون توقيع
      - name: Build Unsigned IPA
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
