workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: 3.19.6 # تحديد إصدار Flutter محدد
      xcode: latest
      cocoapods: 1.11.2
    scripts:
      - name: Update CocoaPods
        script: |
          gem install cocoapods -v 1.11.2
      - name: Install Flutter
        script: | 
          flutter pub get
      - name: Build iOS App
        script: | 
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.app.zip
    publishing:
      email:
        recipients:
          - your_email@example.com
        notify: 
          success: true
          failure: true

