workflows:
  flutter-ios-build:
    name: Build Flutter iOS (Unsigned IPA)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        LC_ALL: en_US.UTF-8
        LANG: en_US.UTF-8

    scripts:
      - name: Fix Theme type errors in app_theme.dart
        script: |
          cd $CM_BUILD_DIR/flutter_app
          sed -i '' -e 's/CardTheme(/CardThemeData(/g' -e 's/TabBarTheme(/TabBarThemeData(/g' lib/theme/app_theme.dart

      - name: Get Flutter dependencies
        script: |
          cd $CM_BUILD_DIR/flutter_app
          flutter clean
          flutter pub get

      - name: Build iOS app (Unsigned)
        script: |
          cd $CM_BUILD_DIR/flutter_app
          flutter build ios --release --no-codesign
          mkdir -p Payload
          cp -R build/ios/iphoneos/*.app Payload/
          cd Payload
          zip -r ../app_unsigned.ipa ./
          cd ..
          rm -rf Payload

    artifacts:
      - flutter_app/app_unsigned.ipa
