workflows:
  react-native-ios-unsigned:
    name: Build React Native iOS (Unsigned IPA)
    environment:
      # إزالة تحديد نسخ Node.js و Xcode للاعتماد على بيئة Codemagic الافتراضية
      # node: 18.x     <-- تم الحذف
      # xcode: latest  <-- تم الحذف

    scripts:
      - name: Install Node.js dependencies
        script: |
          cd $CM_BUILD_DIR
          npm install

      - name: Install CocoaPods dependencies
        script: |
          cd $CM_BUILD_DIR/ios
          pod repo update
          pod install

      - name: Build iOS app (Unsigned)
        script: |
          cd $CM_BUILD_DIR/ios
          xcodebuild clean -workspace InstagramLoginApp.xcworkspace -scheme InstagramLoginApp -configuration Release
          xcodebuild build \
            -workspace InstagramLoginApp.xcworkspace \
            -scheme InstagramLoginApp \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            -derivedDataPath $CM_BUILD_DIR/build/ios

      - name: Create Unsigned IPA
        script: |
          APP_PATH="$CM_BUILD_DIR/build/ios/Build/Products/Release-iphoneos/InstagramLoginApp.app"
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          zip -r InstagramLoginApp_unsigned.ipa Payload
          rm -rf Payload

    artifacts:
      - InstagramLoginApp_unsigned.ipa

    publishing:
      email:
        recipients:
          - you@example.com
