workflows:
  ios_unsigned_build:
    name: iOS Unsigned IPA
    environment:
      flutter: "3.19.5"
      xcode: "15.2"
      cocoapods: "1.15.2"

    scripts:
      - name: Verify Environment
        script: |
          flutter doctor -v
          which pod
          pod --version

      - name: Clean & Setup
        script: |
          flutter clean
          flutter pub get
          rm -rf ios/Pods ios/Podfile.lock

      - name: iOS Preparation
        script: |
          cd ios
          pod repo update
          pod install --verbose
          cd ..
          chmod -R 755 ios/

      - name: Build Unsigned IPA
        script: |
          flutter build ipa \
            --release \
            --no-codesign \
            --dart-define=CODESIGNING_DISABLED=true \
            --verbose

      - name: Verify Artifacts
        script: |
          if ls build/ios/ipa/*.ipa 1> /dev/null 2>&1; then
            echo "✅ IPA generated successfully"
            ls -lh build/ios/ipa/
          else
            echo "❌ IPA file not found!"
            exit 1
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - ios/Runner.xcarchive/**/*
      - ios/Flutter/flutter_export_environment.sh

    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ios/.symlinks
