workflows:
  ios-unsigned-build:
    name: 'iOS Unsigned Build'
    # استخدم جهاز macOS M2 للبناء. يمكنك تغييره إلى mac_pro إذا لزم الأمر.
    instance_type: mac_mini_m2
    environment:
      # استخدم أحدث إصدار مستقر من Flutter.
      flutter: stable
      # استخدم أحدث إصدار من Xcode.
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          # انتقل إلى مجلد ios وقم بتثبيت الـ Pods.
          cd ios
          pod install
      - name: Build unsigned IPA
        script: |
          # قم ببناء التطبيق في وضع الإصدار (release) وبدون توقيع رقمي.
          flutter build ipa --release --no-codesign
    artifacts:
      # حدد مسار ملف IPA الناتج ليكون متاحًا للتحميل.
      - build/ios/ipa/*.ipa

