workflows:
  build-ios-unsigned:
    name: Build iOS (Unsigned IPA)
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Fix Flutter theme API changes
        script: |
          # تعديل CardTheme
          sed -i '' 's/CardTheme(/CardThemeData(/g' lib/theme/app_theme.dart
          # تعديل TabBarTheme
          sed -i '' 's/TabBarTheme(/TabBarThemeData(/g' lib/theme/app_theme.dart

      - name: Build iOS app without code signing
        script: |
          flutter build ios --release --no-codesign

      - name: Create IPA from .app
        script: |
          mkdir -p Payload
          cp -R build/ios/iphoneos/*.app Payload/
          zip -r app.ipa Payload
          rm -rf Payload

    artifacts:
      - app.ipa
    publishing:
      email:
        recipients:
          - you@example.com
